### ISSUE TITLE
Font size and tab size not ideal, and a couple other issues/questions

### ISSUE THREAD

**Issue by drkhero** [akkva/gwfox#1]
Hello! 

Fantastic theme, I absolutely love the vertical tabs option, and I'm so glad to see you back here on Github. However, I'm wondering if it would be possible for you to use something like Sidebery to move the URL bar on the left side like Arc Browser. It's a lot better to have the URL bar on the left, where all the tabs are just like Arc.

Also, not sure if you know, but it might be beneficial to switch to Sidebery for your vertical tabs implementation. Sidebery allows resizing of the sidebar, alongside a couple other things. It's also fully customizable. [Here's an example of Sidebery being used with a custom UI](https://github.com/sirlan-ff00ff/arcticfox-theme). Either way, you've done a fantastic job.

Now for the bugs, I noticed a couple issues with the vertical tabs. First, in your screenshots, the text size and tab size seem a lot more bigger than in the final version. Check screenshot: 
<img width="1599" alt="Screenshot 2024-04-06 at 3 39 52 PM" src="https://github.com/akkva/gwfox/assets/155139404/4fb92b31-a2de-418e-b01c-087b22680423">

Second, the only way to have transparency in the sidebar is to enable 'system auto' in the theme. It's not possible to have transparency if you select light or dark.

Third, watching videos on YouTube on Twitch in full screen will keep the sidebar on the left. It's not a proper full screen.

Fourth, it's not possible to reorder tabs. If I want to change where a tab is and drag it, I can't do that. 

I'm extremely impressed by your work. Seriously, you should be extremely proud of the work you've done here. Good job!

**Comment by akkva** [comment]
首先谢谢你的喜欢和支持

关于你反馈的几个问题我简单说一下

1.字体/标签页大小差异是不是分辨率的问题

2、3的问题已经修复

第4个问题暂时无解

还有就是Sidebery相关的，我之前有出过一版不知道你有没有留意

<img width="1000" alt="3112" src="https://github.com/akkva/gwfox/assets/150437642/a7cebcf6-3cb8-489b-bbf6-2d2b0dd2d476"><br>
等我有空再折腾一下看看

如果你喜欢arc样式这边推荐你可以看一下这个主题[EdgyArc-fr](https://github.com/artsyfriedchicken/EdgyArc-fr)

**Comment by akkva** [comment]
@drkhero 

> I noticed a new bug while using the theme, basically when I bring up mission control on macOS (F3 to bring up mission control), or try resizing the Firefox window, the animation will be very laggy.
Howver, when I i'm no using the theme and use mission control, the animation is very smooth. The lag only happens when using the theme. The fastest way to see the difference is by spamming the mission control button on mac with at least 1 other app opened, and you'll see that the theme has a very very obvious lag in the animation.
I think that the lag may be caused because of the amount of shadow used around the Firefox window. I may be wrong. Let me know if there's a fix!

这个问题在V126中修复了😊

**Comment by akkva** [comment]
[WIP]Arc Style😉

<img width="1000" alt="19 26 30" src="https://github.com/akkva/gwfox/assets/150437642/9dfdbd1a-7c02-4cef-831d-b20a5cf75f32">

**Comment by ghost** [comment]
> [WIP]Arc Style😉

Wow nice work! This looks amazing! Let me know how to enable the Arc Style 👏👍

**Comment by akkva** [comment]
> > [WIP]Arc Style😉
> 
> Wow nice work! This looks amazing! Let me know how to enable the Arc Style 👏👍

🥳完成了，快来试试

**Comment by ghost** [comment]
> > > [WIP]Arc Style😉
> > 
> > 
> > Wow nice work! This looks amazing! Let me know how to enable the Arc Style 👏👍
> 
> 🥳完成了，快来试试

I just tried, and wow, I'm incredibly impressed. Really amazing work on the URL integration on the left. The popup animation, and everything just looks perfect!  Fantastic job!

Only a couple things to fix though:

1. The URL bar shouldn't be showing "https", or the padlock icon. It should only show the URL, just like on Arc. This way we have a lot more space to see the full URL properly:
<img width="264" alt="Screenshot 2024-04-21 at 6 51 50 PM" src="https://github.com/akkva/gwfox/assets/155139404/51d9f13c-644e-4f89-8fce-eb380c299f1b">

2. Could you show me how to change the color of a selected tab ? On Arc, the selected tab is fully white, whereas on here it's a little bit grey. I prefect the selected tab to be fully white. rgb (255,255,255)

3. There's also a couple of small bugs I found, I'll let you know about them later

**Comment by akkva** [comment]
> > > > [WIP]Arc Style😉
> > > 
> > > 
> > > Wow nice work! This looks amazing! Let me know how to enable the Arc Style 👏👍
> > 
> > 
> > 🥳完成了，快来试试
> 
> I just tried, and wow, I'm incredibly impressed. Really amazing work on the URL integration on the left. The popup animation, and everything just looks perfect! Fantastic job!
> 
> Only a couple things to fix though:
> 
>     1. The URL bar shouldn't be showing "https", or the padlock icon. It should only show the URL, just like on Arc. This way we have a lot more space to see the full URL properly:
> 
> 
> <img alt="Screenshot 2024-04-21 at 6 51 50 PM" width="264" src="https://private-user-images.githubusercontent.com/155139404/324290307-51d9f13c-644e-4f89-8fce-eb380c299f1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NDEwMzcsIm5iZiI6MTcxMzc0MDczNywicGF0aCI6Ii8xNTUxMzk0MDQvMzI0MjkwMzA3LTUxZDlmMTNjLTY0NGUtNGY4OS04ZmNlLWViMzgwYzI5OWYxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQyMzA1MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmU4ZTJhOTdhN2RhMzEyOTdjMDc4YTczYjc0MDZiOWNjOWI2MzA3ZWM4ZDI1MThiYmUwYWU0ZWQ0NzhkMjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HmDbernF18Tv8P2xqPob0plg8oYqp8_dSkFehIDUI-8">
> 
>     2. Could you show me how to change the color of a selected tab ? On Arc, the selected tab is fully white, whereas on here it's a little bit grey. I prefect the selected tab to be fully white. rgb (255,255,255)
> 
>     3. There's also a couple of small bugs I found, I'll let you know about them later

1. 不显示https `about:config > browser.urlbar.trimHttps > true`

2. userChrome.css里搜索 `background: linear-gradient(#f0f0f4, #ecedf2) !important;`

**Comment by ghost** [comment]
> > > > > [WIP]Arc Style😉
> > > > 
> > > > 
> > > > Wow nice work! This looks amazing! Let me know how to enable the Arc Style 👏👍
> > > 
> > > 
> > > 🥳完成了，快来试试
> > 
> > 
> > I just tried, and wow, I'm incredibly impressed. Really amazing work on the URL integration on the left. The popup animation, and everything just looks perfect! Fantastic job!
> > Only a couple things to fix though:
> > ```
> > 1. The URL bar shouldn't be showing "https", or the padlock icon. It should only show the URL, just like on Arc. This way we have a lot more space to see the full URL properly:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="Screenshot 2024-04-21 at 6 51 50 PM" width="264" src="https://private-user-images.githubusercontent.com/155139404/324290307-51d9f13c-644e-4f89-8fce-eb380c299f1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NDEwMzcsIm5iZiI6MTcxMzc0MDczNywicGF0aCI6Ii8xNTUxMzk0MDQvMzI0MjkwMzA3LTUxZDlmMTNjLTY0NGUtNGY4OS04ZmNlLWViMzgwYzI5OWYxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQyMzA1MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmU4ZTJhOTdhN2RhMzEyOTdjMDc4YTczYjc0MDZiOWNjOWI2MzA3ZWM4ZDI1MThiYmUwYWU0ZWQ0NzhkMjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HmDbernF18Tv8P2xqPob0plg8oYqp8_dSkFehIDUI-8">
> > ```
> > 2. Could you show me how to change the color of a selected tab ? On Arc, the selected tab is fully white, whereas on here it's a little bit grey. I prefect the selected tab to be fully white. rgb (255,255,255)
> > 
> > 3. There's also a couple of small bugs I found, I'll let you know about them later
> > ```
> 
>     1. 不显示https `about:config > browser.urlbar.trimHttps > true`
> 
>     2. userChrome.css里搜索 `background: linear-gradient(#f0f0f4, #ecedf2) !important;`



Alright, so here are few of the bugs I've found so far:

1. There's an invisible bar at the top to be able to drag the browser window around, but this invisible bar is way too big, causing it to interfere with most websites. For instance, here I'm trying to select some text on Youtube, and I'm simply unable to do so because of the invisible bar:

https://github.com/akkva/gwfox/assets/155139404/b4bb33d6-bb3e-4c6e-b412-46942cecb374


2. When I open a new blank page tab, this is how it looks like (there's a random grey line in the middle and the window isn't taking the full height of the page): 

<img width="1428" alt="new Tab" src="https://github.com/akkva/gwfox/assets/155139404/991bfb67-6c62-4433-9e97-2c81b40cf1cb">


3. When I hover over the URL bar, there's a few icons that pop up. How can I make it so that no icon pops up when I hover over the URL ? 

https://github.com/akkva/gwfox/assets/155139404/a5e561c3-0716-48aa-9230-215d29de2426

**Comment by akkva** [comment]
> > > > > > [WIP]Arc Style😉
> > > > > 
> > > > > 
> > > > > Wow nice work! This looks amazing! Let me know how to enable the Arc Style 👏👍
> > > > 
> > > > 
> > > > 🥳完成了，快来试试
> > > 
> > > 
> > > I just tried, and wow, I'm incredibly impressed. Really amazing work on the URL integration on the left. The popup animation, and everything just looks perfect! Fantastic job!
> > > Only a couple things to fix though:
> > > ```
> > > 1. The URL bar shouldn't be showing "https", or the padlock icon. It should only show the URL, just like on Arc. This way we have a lot more space to see the full URL properly:
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > <img alt="Screenshot 2024-04-21 at 6 51 50 PM" width="264" src="https://private-user-images.githubusercontent.com/155139404/324290307-51d9f13c-644e-4f89-8fce-eb380c299f1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NDEwMzcsIm5iZiI6MTcxMzc0MDczNywicGF0aCI6Ii8xNTUxMzk0MDQvMzI0MjkwMzA3LTUxZDlmMTNjLTY0NGUtNGY4OS04ZmNlLWViMzgwYzI5OWYxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQyMzA1MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmU4ZTJhOTdhN2RhMzEyOTdjMDc4YTczYjc0MDZiOWNjOWI2MzA3ZWM4ZDI1MThiYmUwYWU0ZWQ0NzhkMjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HmDbernF18Tv8P2xqPob0plg8oYqp8_dSkFehIDUI-8">
> > > ```
> > > 2. Could you show me how to change the color of a selected tab ? On Arc, the selected tab is fully white, whereas on here it's a little bit grey. I prefect the selected tab to be fully white. rgb (255,255,255)
> > > 
> > > 3. There's also a couple of small bugs I found, I'll let you know about them later
> > 
> > 
> > ```
> > 1. 不显示https `about:config > browser.urlbar.trimHttps > true`
> > 
> > 2. userChrome.css里搜索 `background: linear-gradient(#f0f0f4, #ecedf2) !important;`
> > ```
> 
> Alright, so here are few of the bugs I've found so far:
> 
>     1. There's an invisible bar at the top to be able to drag the browser window around, but this invisible bar is way too big, causing it to interfere with most websites. For instance, here I'm trying to select some text on Youtube, and I'm simply unable to do so because of the invisible bar:
> 
> 
> buggin.mp4
> 
>     2. When I open a new blank page tab, this is how it looks like (there's a random grey line in the middle and the window isn't taking the full height of the page):
> 
> 
> <img alt="new Tab" width="1428" src="https://private-user-images.githubusercontent.com/155139404/324433857-991bfb67-6c62-4433-9e97-2c81b40cf1cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODY5MTIsIm5iZiI6MTcxMzc4NjYxMiwicGF0aCI6Ii8xNTUxMzk0MDQvMzI0NDMzODU3LTk5MWJmYjY3LTZjNjItNDQzMy05ZTk3LTJjODFiNDBjZjFjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxMTUwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTVhOTJiMmE1NDM5N2MyNTQ0OGZkMjY5M2IyYTgyYzMxNjgyMWJiMTRiMzRkYTA0N2EzZjhmMjk4MzMyMzYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VSb5h-De_dPBBCD21T6auNpAmqyJLr8nbJNOoZlydFs">
> 
>     3. When I hover over the URL bar, there's a few icons that pop up. How can I make it so that no icon pops up when I hover over the URL ?
> 
> 
> icons.mp4

1. 这个问题我做了优化，顶部预留了10px左右来拖拽移动窗口，经过测试应该不会影响文本选择了

2. 这个问题彻底修复了

3.这个需求要改的东西不少，你确定不需要这些图标的操作吗？

**Comment by ghost** [comment]
> > > > > > > [WIP]Arc Style😉
> > > > > > 
> > > > > > 
> > > > > > Wow nice work! This looks amazing! Let me know how to enable the Arc Style 👏👍
> > > > > 
> > > > > 
> > > > > 🥳完成了，快来试试
> > > > 
> > > > 
> > > > I just tried, and wow, I'm incredibly impressed. Really amazing work on the URL integration on the left. The popup animation, and everything just looks perfect! Fantastic job!
> > > > Only a couple things to fix though:
> > > > ```
> > > > 1. The URL bar shouldn't be showing "https", or the padlock icon. It should only show the URL, just like on Arc. This way we have a lot more space to see the full URL properly:
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > <img alt="Screenshot 2024-04-21 at 6 51 50 PM" width="264" src="https://private-user-images.githubusercontent.com/155139404/324290307-51d9f13c-644e-4f89-8fce-eb380c299f1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NDEwMzcsIm5iZiI6MTcxMzc0MDczNywicGF0aCI6Ii8xNTUxMzk0MDQvMzI0MjkwMzA3LTUxZDlmMTNjLTY0NGUtNGY4OS04ZmNlLWViMzgwYzI5OWYxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQyMzA1MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmU4ZTJhOTdhN2RhMzEyOTdjMDc4YTczYjc0MDZiOWNjOWI2MzA3ZWM4ZDI1MThiYmUwYWU0ZWQ0NzhkMjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HmDbernF18Tv8P2xqPob0plg8oYqp8_dSkFehIDUI-8">
> > > > ```
> > > > 2. Could you show me how to change the color of a selected tab ? On Arc, the selected tab is fully white, whereas on here it's a little bit grey. I prefect the selected tab to be fully white. rgb (255,255,255)
> > > > 
> > > > 3. There's also a couple of small bugs I found, I'll let you know about them later
> > > 
> > > 
> > > ```
> > > 1. 不显示https `about:config > browser.urlbar.trimHttps > true`
> > > 
> > > 2. userChrome.css里搜索 `background: linear-gradient(#f0f0f4, #ecedf2) !important;`
> > > ```
> > 
> > 
> > Alright, so here are few of the bugs I've found so far:
> > ```
> > 1. There's an invisible bar at the top to be able to drag the browser window around, but this invisible bar is way too big, causing it to interfere with most websites. For instance, here I'm trying to select some text on Youtube, and I'm simply unable to do so because of the invisible bar:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > buggin.mp4
> > ```
> > 2. When I open a new blank page tab, this is how it looks like (there's a random grey line in the middle and the window isn't taking the full height of the page):
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="new Tab" width="1428" src="https://private-user-images.githubusercontent.com/155139404/324433857-991bfb67-6c62-4433-9e97-2c81b40cf1cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODY5MTIsIm5iZiI6MTcxMzc4NjYxMiwicGF0aCI6Ii8xNTUxMzk0MDQvMzI0NDMzODU3LTk5MWJmYjY3LTZjNjItNDQzMy05ZTk3LTJjODFiNDBjZjFjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQxMTUwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTVhOTJiMmE1NDM5N2MyNTQ0OGZkMjY5M2IyYTgyYzMxNjgyMWJiMTRiMzRkYTA0N2EzZjhmMjk4MzMyMzYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VSb5h-De_dPBBCD21T6auNpAmqyJLr8nbJNOoZlydFs">
> > ```
> > 3. When I hover over the URL bar, there's a few icons that pop up. How can I make it so that no icon pops up when I hover over the URL ?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > icons.mp4
> 
>     1. 这个问题我做了优化，顶部预留了10px左右来拖拽移动窗口，经过测试应该不会影响文本选择了
> 
>     2. 这个问题彻底修复了
> 
> 
> 3.这个需求要改的东西不少，你确定不需要这些图标的操作吗？

I can confirm all of this is fixed! Good job!

Currently, the only issue remaining is that you can't re-order your tabs. It won't let me move a tab up or down. Do you think there's any fix for this ?

**Comment by akkva** [comment]
> I can confirm all of this is fixed! Good job!
Currently, the only issue remaining is that you can't re-order your tabs. It won't let me move a tab up or down. Do you think there's any fix for this ?

目前能做的就是用[Move Tab Hotkeys](https://addons.mozilla.org/en-US/firefox/addon/move-tab-hotkeys)这个扩展添加快捷键来移动

**Comment by ghost** [comment]
> > I can confirm all of this is fixed! Good job!
> > Currently, the only issue remaining is that you can't re-order your tabs. It won't let me move a tab up or down. Do you think there's any fix for this ?
> 
> 目前能做的就是用[Move Tab Hotkeys](https://addons.mozilla.org/en-US/firefox/addon/move-tab-hotkeys)这个扩展添加快捷键来移动

Alright thanks, I'll look into it. By the way, consider making your theme compatible with Sidebery. It might be a much easier solution considering Sidebery takes care of the Javascript side, which includes being able to re-order tabs, and also resize the sidebar.

**Comment by akkva** [comment]
> > > I can confirm all of this is fixed! Good job!
> > > Currently, the only issue remaining is that you can't re-order your tabs. It won't let me move a tab up or down. Do you think there's any fix for this ?
> > 
> > 
> > 目前能做的就是用[Move Tab Hotkeys](https://addons.mozilla.org/en-US/firefox/addon/move-tab-hotkeys)这个扩展添加快捷键来移动
> 
> Alright thanks, I'll look into it. By the way, consider making your theme compatible with Sidebery. It might be a much easier solution considering Sidebery takes care of the Javascript side, which includes being able to re-order tabs, and also resize the sidebar.

Sidebery做不到透明背景，没有系统半透明效果加持视觉效果差很多，这个主题的出发点就是为了好看，目前的效果已经是我能做的极致了，其实我也是小白来着😊

**Comment by ghost** [comment]
> > > > I can confirm all of this is fixed! Good job!
> > > > Currently, the only issue remaining is that you can't re-order your tabs. It won't let me move a tab up or down. Do you think there's any fix for this ?
> > > 
> > > 
> > > 目前能做的就是用[Move Tab Hotkeys](https://addons.mozilla.org/en-US/firefox/addon/move-tab-hotkeys)这个扩展添加快捷键来移动
> > 
> > 
> > Alright thanks, I'll look into it. By the way, consider making your theme compatible with Sidebery. It might be a much easier solution considering Sidebery takes care of the Javascript side, which includes being able to re-order tabs, and also resize the sidebar.
> 
> Sidebery做不到透明背景，没有系统半透明效果加持视觉效果差很多，这个主题的出发点就是为了好看，目前的效果已经是我能做的极致了，其实我也是小白来着😊



No worries. You're a pro in my book 👍😄

By the way, can you provide a quick and easy way to change the color of the sidebar just like in Arc?:

<img width="689" alt="color" src="https://github.com/akkva/gwfox/assets/155139404/57496ca4-2844-4d10-97d7-deaf200a474f">

**Comment by akkva** [comment]
> > > > > I can confirm all of this is fixed! Good job!
> > > > > Currently, the only issue remaining is that you can't re-order your tabs. It won't let me move a tab up or down. Do you think there's any fix for this ?
> > > > 
> > > > 
> > > > 目前能做的就是用[Move Tab Hotkeys](https://addons.mozilla.org/en-US/firefox/addon/move-tab-hotkeys)这个扩展添加快捷键来移动
> > > 
> > > 
> > > Alright thanks, I'll look into it. By the way, consider making your theme compatible with Sidebery. It might be a much easier solution considering Sidebery takes care of the Javascript side, which includes being able to re-order tabs, and also resize the sidebar.
> > 
> > 
> > Sidebery做不到透明背景，没有系统半透明效果加持视觉效果差很多，这个主题的出发点就是为了好看，目前的效果已经是我能做的极致了，其实我也是小白来着😊
> 
> No worries. You're a pro in my book 👍😄
> 
> By the way, can you provide a quick and easy way to change the color of the sidebar just like in Arc?:
> <img alt="color" width="689" src="https://private-user-images.githubusercontent.com/155139404/326295786-57496ca4-2844-4d10-97d7-deaf200a474f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNjc2MjQsIm5iZiI6MTcxNDM2NzMyNCwicGF0aCI6Ii8xNTUxMzk0MDQvMzI2Mjk1Nzg2LTU3NDk2Y2E0LTI4NDQtNGQxMC05N2Q3LWRlYWYyMDBhNDc0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQwNTA4NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMjU4Y2E0N2JkOTNiYTdiNjVkN2EzMTQ5YzJkY2I4Y2EzNmNlYTdjZWNjNGVmYmFjZDA5OTYzYjk5YTI5NTM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4d3qTlVJ56Y5cHT18h0g2VS-A9MKlM0oqLyxJAPdIC0">

这个效果改css并不麻烦，不幸的是并没有现成的扩展让你可以简单快速的定制😎

**Comment by drkhero** [comment]
> 这个效果改css并不麻烦，不幸的是并没有现成的扩展让你可以简单快速的定制😎

I made a few changes to the theme color, it looks perfect now 🙌
<img width="1690" alt="scr" src="https://github.com/akkva/gwfox/assets/155139404/9c279cc9-3948-424c-82ec-9fc14ebb8c01">

**Comment by ghost** [comment]
> 这个效果改css并不麻烦，不幸的是并没有现成的扩展让你可以简单快速的定制😎

I made a few changes to the theme color, it looks perfect now 🙌


<img width="1568" alt="scr3" src="https://github.com/akkva/gwfox/assets/155139404/c54635f4-864a-449f-ba10-2197bec38771">

**Comment by ghost** [comment]
Hello @akkva there's something I'm wondering if you can implement.

Here's a video of the difference between the search UI on Arc Browser and the search UI on your Firefox theme. I'm wondering if you could implement the Arc Browser search UI shown in this video into the Firefox theme. I think it looks really good, and it would be awesome if you could put it into the Firefox theme. Let me know if it's possible :)

https://github.com/akkva/gwfox/assets/155139404/05a5e2ab-3a23-4b91-ba55-330a2cca09b4

**Comment by ejkarne** [comment]
While I don't personally use gwfox (I need Sidebery to replicate Spaces) I'm still very impressed with how well gwfox mimic's Arc. A while back the Arc team emailed me for a survey hosted on Figma but allowed it to be copied and edited. I've based my personal Sidebery theme on that template and I figured you may also find it useful. [link](https://www.figma.com/file/YOL0fczo7E5FAupXJTW8OV/Shared-Link-Prototypes-(survey)-(Copy)?type=design&node-id=0%3A1&mode=design&t=qemzBkVEkdt6MJZu-1)

**Comment by ghost** [comment]
> While I don't personally use gwfox (I need Sidebery to replicate Spaces) I'm still very impressed with how well gwfox mimic's Arc. A while back the Arc team emailed me for a survey hosted on Figma but allowed it to be copied and edited. I've based my personal Sidebery theme on that template and I figured you may also find it useful. [link](https://www.figma.com/file/YOL0fczo7E5FAupXJTW8OV/Shared-Link-Prototypes-(survey)-(Copy)?type=design&node-id=0%3A1&mode=design&t=qemzBkVEkdt6MJZu-1)

You could also replicate spaces using native Firefox containers.

How does your Sidebery theme look like ?  I'd say we're about 80% of the way there to completely nailing the Arc experience on Firefox with gwfox's theme. There's a few things that need to be polished and done, like the command bar and the search UI, but we're really almost there.

**Comment by ejkarne** [comment]
> > While I don't personally use gwfox (I need Sidebery to replicate Spaces) I'm still very impressed with how well gwfox mimic's Arc. A while back the Arc team emailed me for a survey hosted on Figma but allowed it to be copied and edited. I've based my personal Sidebery theme on that template and I figured you may also find it useful. [link](https://www.figma.com/file/YOL0fczo7E5FAupXJTW8OV/Shared-Link-Prototypes-(survey)-(Copy)?type=design&node-id=0%3A1&mode=design&t=qemzBkVEkdt6MJZu-1)
> 
> You could also replicate spaces using native Firefox containers.
> 
> How does your Sidebery theme look like ? I'd say we're about 80% of the way there to completely nailing the Arc experience on Firefox with gwfox's theme. There's a few things that need to be polished and done, like the command bar and the search UI, but we're really almost there.

Sidebery lets me switch between "spaces" with different assigned containers akin to Arc, my understanding is that without it I'm just able to assign specific tabs to containers instead.

My Sidebery theme currently looks like this,
![SCR-20240510-lipk](https://github.com/akkva/gwfox/assets/4615298/6f2187a0-b0ce-44f9-baa8-448014c0f72e)
The Figma template was helpful since it let me find the exact measurements of some items and exact shadow values without having to pixel peep. Though I'm not going for a perfect recreation. I should also note that I'm using [EdgyArc-fr](https://github.com/artsyfriedchicken/EdgyArc-fr) which accomplishes translucency on Sidebery by setting the opacity of Sidebery itself which isn't exactly ideal but at least works.

**Comment by ghost** [comment]
> Though I'm not going for a perfect recreation. I should also note that I'm using [EdgyArc-fr](https://github.com/artsyfriedchicken/EdgyArc-fr) which accomplishes translucency on Sidebery by setting the opacity of Sidebery itself which isn't exactly ideal but at least works.



Nice. akkva's main reason for not using Sidebery was because he didn't think it was possible to achieve transparency on Sidebery. Turns out it is.

**Comment by akkva** [comment]
> Hello @akkva there's something I'm wondering if you can implement.
> 
> Here's a video of the difference between the search UI on Arc Browser and the search UI on your Firefox theme. I'm wondering if you could implement the Arc Browser search UI shown in this video into the Firefox theme. I think it looks really good, and it would be awesome if you could put it into the Firefox theme. Let me know if it's possible :)
> final3.mp4

在我看来你的视频展示两者并没有多大区别，无非就是多了一些firefox建议网址还有底部工具条
所有我没有很明白你的诉求，你是想让firefox地址栏搜索界面去掉一些元素显示更简洁一点？
