### ISSUE TITLE
好喜欢你的主题，但是有没有办法做一个url在最上面最中间的版本 ?

### ISSUE THREAD

**Issue by Petittux1** [akkva/gwfox#3]
好喜欢你的主题，但是有没有办法做一个url在最上面最中间的版本吗 ? 就像arcwtf, url bar是居中的
我认为你这个主题更稳定也更清晰与好看，唯一一个问题就是url不是在我喜欢的地方。
要是有办法混合两个主题，我会觉得特别棒。
(我是法国人但是我会中文，希望能get得到我写的）加油 !

**Comment by akkva** [comment]
谢谢喜欢，你使用的是Windows吗？关于你要的布局，要调整不少东西得花点时间，等我有空看一下，你的中文很棒完全可以get🙂

**Comment by Petittux1** [comment]
刚刚忘记写，我用的是windows没错

太棒了 ！对，我自己尝试了混合两个userchrome.css , 改了navbar成arcwtf navbar, 这个我成功地修改了，urlbar会出现在最上面并居中，但是问题是所有的tabs还有其他的一些键（buttons)会在同一个地方出现。我并不专业，我是第一次尝试修改css也没有什么相关的知识。反正不只是要改navbar，我猜也要把很多其他东西的位置调在无法可看的地方 ？
谢谢你 ！没事儿我就耐心等待，我就关注你的 repository !

**Comment by akkva** [comment]
完成了，详见#4

**Comment by Petittux1** [comment]
太好了太好了 ！我试试看 ！谢谢你 ！

**Comment by Petittux1** [comment]
我刚刚试了一下，非常棒，用白色主题没问题但是当在用火狐官方黑色主题，左边跟上面的颜色不同。请问你用什么主题 ? 我觉得很好看 ! 我试了几个其他的主题也不兼容，但是可能只有几个主题跟你的mod兼容 ?
是这样 : 
![image](https://github.com/user-attachments/assets/5bd9367b-608a-4ce1-bbcb-bc0837685b4e)

然后白色主题 

![image](https://github.com/user-attachments/assets/5667388a-f60b-448c-a210-b30a683544f3)

**Comment by Petittux1** [comment]
还有一个问题是不知道如何让我 刷新 后退 前进键重新出现
截图：
![image](https://github.com/user-attachments/assets/98339aeb-c6df-4498-b156-1dcbda9b1c6f)

**Comment by Petittux1** [comment]
非常棒，我一开始以为有很多问题，但是都怪我忘了加ressource 和 usercontent...... 现在一切都很好哈哈哈
感谢你，你速度很快 !

**Comment by Petittux1** [comment]
有没有办法也把以前mac式按键保留这个新版本里 ?
我说的是这些
![image](https://github.com/user-attachments/assets/4f8f8936-d32a-41e5-97fb-1ff335f7d161)
因为目前还是这样 :
![image](https://github.com/user-attachments/assets/726c8c73-d57f-4d64-a344-27f4c54aff90)

我觉得不管是在左边还是右边都不错

**Comment by akkva** [comment]
> 有没有办法也把以前mac式按键保留这个新版本里 ? 我说的是这些
> 我觉得不管是在左边还是右边都不错

因为开启了mica特效，这里的窗口控件是系统主题的，除非修改系统主题不然无法定制或隐藏。

**Comment by gouravraghuwanshi** [comment]
@Petittux1 HI can you please share you chrome folder, cause it looks COOOOL.
